version: '3'
services:

  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - mongodb

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodata: